#ifndef CONSTANTS_CUH
#define CONSTANTS_CUH

#ifndef WORLD_SIZE
#define WORLD_SIZE 512
#endif

#ifndef MAX_CREATURES
#define MAX_CREATURES 200000
#endif

#define GENOME_SIZE 256
#define GENOME_LENGTH GENOME_SIZE
#define CENTROID_GENES 32
#define MAX_PHYLO_NODES 10000
#define POOL_ALIGNMENT 256
#define MAX_STREAMS 16

#define WATER_LEVEL 0.35f
#define MAX_ENERGY 2.0f
#define REPRODUCE_COOLDOWN_TIME 50.0f
#define REPRODUCE_ENERGY_COST 0.2f

// Terrain constants
#define TERRAIN_MAX_HEIGHT 100.0f
#define TERRAIN_NOISE_FREQ 0.005f
#define TERRAIN_NOISE_OCTAVES 8
#define TERRAIN_NOISE_LACUNARITY 2.0f
#define TERRAIN_NOISE_PERSISTENCE 0.5f

// Erosion Constants
#define EROSION_MAX_LIFETIME 30
#define EROSION_INERTIA 0.05f
#define EROSION_SEDIMENT_CAP 4.0f
#define EROSION_DEPOSIT_SPEED 0.3f
#define EROSION_ERODE_SPEED 0.3f
#define EROSION_EVAPORATE_SPEED 0.01f
#define GRAVITY 9.81f
#define EROSION_MIN_SLOPE 0.01f

// Biome definitions
#define BIOME_COUNT 13
#define BIOME_DEEP_OCEAN 0.0f
#define BIOME_OCEAN 1.0f
#define BIOME_BEACH 2.0f
#define BIOME_SWAMP 3.0f
#define BIOME_GRASSLAND 4.0f
#define BIOME_FOREST 5.0f
#define BIOME_RAINFOREST 6.0f
#define BIOME_SAVANNA 7.0f
#define BIOME_DESERT 8.0f
#define BIOME_TAIGA 9.0f
#define BIOME_TUNDRA 10.0f
#define BIOME_MOUNTAIN 11.0f
#define BIOME_SNOW_PEAK 12.0f

#define BLOCK_SIZE_2D 16
#define BLOCK_SIZE_1D 256

// Gene indices
#define GENE_SIZE         0
#define GENE_SPEED        1
#define GENE_SENSE        2
#define GENE_COLOR_R      3
#define GENE_COLOR_G      4
#define GENE_COLOR_B      5
#define GENE_ARMOR        6
#define GENE_LIMBS        7
#define GENE_JAW          8
#define GENE_CLAW         9

#define GENE_DIET         32
#define GENE_EFFICIENCY   33
#define GENE_LIFESPAN     34
#define GENE_REPRO_RATE   35
#define GENE_TEMP_TOL     36
#define GENE_WATER_REQ    37
#define GENE_REPRO_COST   38
#define GENE_MATURITY     39
#define GENE_MATE_SELECT  40

#define GENE_AGGRO        64
#define GENE_SOCIAL       65
#define GENE_CURIOSITY    66
#define GENE_FEAR         67
#define GENE_TERRITORIAL  68
#define GENE_MUTATION_RATE     69
#define GENE_MUTATION_STRENGTH 70
#define GENE_ACTIVATION_TYPE 96

#ifndef NEURAL_INPUT_SIZE
#define NEURAL_INPUT_SIZE 24
#endif
#ifndef NEURAL_HIDDEN1_SIZE
#define NEURAL_HIDDEN1_SIZE 32
#endif
#ifndef NEURAL_HIDDEN2_SIZE
#define NEURAL_HIDDEN2_SIZE 16
#endif
#ifndef NEURAL_OUTPUT_SIZE
#define NEURAL_OUTPUT_SIZE 8
#endif
#ifndef NEURAL_WEIGHT_COUNT
#define NEURAL_WEIGHT_COUNT ( \
    (NEURAL_INPUT_SIZE + 1) * NEURAL_HIDDEN1_SIZE + \
    (NEURAL_HIDDEN1_SIZE + 1) * NEURAL_HIDDEN2_SIZE + \
    (NEURAL_HIDDEN2_SIZE + 1) * NEURAL_OUTPUT_SIZE \
)
#endif

#define WARP_SIZE 32
#define W1_OFFSET 0
#define W1_SIZE   (NEURAL_INPUT_SIZE * NEURAL_HIDDEN1_SIZE)
#define B1_OFFSET (W1_SIZE)
#define B1_SIZE   (NEURAL_HIDDEN1_SIZE)
#define W2_OFFSET (B1_OFFSET + B1_SIZE)
#define W2_SIZE   (NEURAL_HIDDEN1_SIZE * NEURAL_HIDDEN2_SIZE)
#define B2_OFFSET (W2_OFFSET + W2_SIZE)
#define B2_SIZE   (NEURAL_HIDDEN2_SIZE)
#define W3_OFFSET (B2_OFFSET + B2_SIZE)
#define W3_SIZE   (NEURAL_HIDDEN2_SIZE * NEURAL_OUTPUT_SIZE)
#define B3_OFFSET (W3_OFFSET + W3_SIZE)
#define B3_SIZE   (NEURAL_OUTPUT_SIZE)
#define TOTAL_USED_WEIGHTS (B3_OFFSET + B3_SIZE)
#define SMEM_PER_CREATURE (NEURAL_INPUT_SIZE + NEURAL_HIDDEN1_SIZE + NEURAL_HIDDEN2_SIZE + NEURAL_OUTPUT_SIZE + TOTAL_USED_WEIGHTS)
#define NEURAL_BLOCK_SIZE 256
#define NEURAL_CREATURES_PER_BLOCK (NEURAL_BLOCK_SIZE / WARP_SIZE)

#endif